# .readthedocs.yaml
# REQUIRED: Configuration file format version
version: 2

# Configuration for the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # Python dependencies installation (use requirements.txt)
  python:
    install:
      - requirements: requirements.txt  # Corrected position of the install block

# Configuration for the Sphinx documentation tool
sphinx:
  # Path to your configuration file (assumes it's in the root)
  configuration: conf.py
